# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestOne.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(346, 303)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(54, 70, 61, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(54, 110, 61, 31))
        self.label_2.setObjectName("label_2")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(120, 10, 64, 23))
        self.lcdNumber.setProperty("intValue", 7)
        self.lcdNumber.setObjectName("lcdNumber")
        self.Performance = QtWidgets.QProgressBar(self.centralwidget)
        self.Performance.setGeometry(QtCore.QRect(50, 150, 201, 21))
        self.Performance.setProperty("value", 57)
        self.Performance.setObjectName("Performance")
        self.clickMe = QtWidgets.QPushButton(self.centralwidget)
        self.clickMe.setGeometry(QtCore.QRect(140, 180, 56, 17))
        self.clickMe.setObjectName("clickMe")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 346, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile_Upload = QtWidgets.QMenu(self.menubar)
        self.menuFile_Upload.setObjectName("menuFile_Upload")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile_Upload.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "USER:"))
        self.label_2.setText(_translate("MainWindow", "PASSWORD:"))
        self.clickMe.setText(_translate("MainWindow", "Click ME"))
        self.menuFile_Upload.setTitle(_translate("MainWindow", "File Upload"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
